# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

install:
  - npx yarn install && npx yarn build

language: node_js
node_js:
  - 'lts/*'
